version: '3.8'
services:
  db:
    image: postgres:latest
    restart: unless-stopped
    tty: true
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
  redis:
    image: redislabs/rejson:latest
    container_name: redis
    restart: unless-stopped
    tty: true
    ports:
      - "6379:6379"