version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: 'rabbitmq'
    environment:
      RABBITMQ_DEFAULT_USER: 'root'
      RABBITMQ_DEFAULT_PASS: 'root'
    ports:
      - "5672:5672"
      - "15672:15672"
